---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{DEVICE_NAME}}-{{DEVICE_ID}}-configmap
  namespace: device-apps
data:
  device.yaml: |
    device_id: {{DEVICE_ID}}
    device_name: {{DEVICE_NAME}}
    
